# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='H5PContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('json_content', models.TextField()),
                ('embed_type', models.CharField(max_length=128)),
                ('disable', models.BooleanField(default=False)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('license', models.CharField(blank=True, max_length=7)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('filtered', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='H5PContentLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('dynamic', 'dynamic'), ('preloaded', 'preloaded'), ('editor', 'editor')], default='preloaded', max_length=128)),
                ('weight', models.IntegerField(default=999999)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5p.H5PContent')),
            ],
        ),
        migrations.CreateModel(
            name='H5PContentUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('data', models.TextField()),
                ('preloaded', models.BooleanField(default=False)),
                ('delete_on_content_change', models.BooleanField(default=False)),
                ('main_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_content', to='h5p.H5PContent')),
                ('sub_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_content', to='h5p.H5PContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='H5PCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=128)),
                ('library_version', models.CharField(max_length=32)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='H5PEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('type', models.CharField(max_length=64)),
                ('sub_type', models.CharField(max_length=64)),
                ('content_title', models.CharField(max_length=255)),
                ('library_name', models.CharField(max_length=128)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5p.H5PContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='H5PFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h5p_file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='H5PLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_url', models.CharField(max_length=1000)),
                ('machine_name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('major_version', models.IntegerField()),
                ('minor_version', models.IntegerField()),
                ('patch_version', models.IntegerField()),
                ('runnable', models.BooleanField(default=True)),
                ('fullscreen', models.BooleanField(default=False)),
                ('embed_types', models.CharField(default='', max_length=255)),
                ('preloaded_js', models.TextField(blank=True)),
                ('preloaded_css', models.TextField(blank=True)),
                ('restricted', models.BooleanField(default=False)),
                ('semantics', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='H5PLibraryDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('dynamic', 'dynamic'), ('preloaded', 'preloaded'), ('editor', 'editor')], default='preloaded', max_length=128)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5p.H5PLibrary')),
                ('required_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_library', to='h5p.H5PLibrary')),
            ],
        ),
        migrations.CreateModel(
            name='H5PLibraryLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=32)),
                ('language_json', models.TextField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5p.H5PLibrary')),
            ],
        ),
        migrations.CreateModel(
            name='H5PPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=True)),
                ('finished', models.BooleanField(default=False)),
                ('points', models.IntegerField()),
                ('max_points', models.IntegerField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5p.H5PContent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='h5pcontentlibrary',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5p.H5PLibrary'),
        ),
        migrations.AddField(
            model_name='h5pcontent',
            name='main_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h5p.H5PLibrary'),
        ),
    ]
