# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5p', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='h5pcontent',
            name='status',
            field=models.CharField(default='in progress', max_length=16),
        ),
    ]
