# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h5p', '0002_h5pcontent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='h5pfile',
            name='mime_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
