# Generated by Django 2.2.7 on 2019-11-24 20:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('h5pp', '0003_auto_20191124_2053'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('certificate_title', models.CharField(blank=True, max_length=400, verbose_name='Certificate Title')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('org_type', models.CharField(choices=[('school', 'School'), ('municipality', 'Municipality'), ('private employer', 'Private Employer')], max_length=100, verbose_name='Organization Type')),
                ('training_year_start', models.DateField(verbose_name='Training Year Start')),
                ('organization_password', models.CharField(blank=True, max_length=256, null=True, verbose_name='Training Password')),
                ('billing_enabled', models.BooleanField(default=False, verbose_name='Billing Enabled')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job Title')),
                ('employee_type', models.CharField(blank=True, choices=[('professional', 'Professional'), ('non-professional', 'Non-professional'), ('default', 'Default')], max_length=100, verbose_name='Employee Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=16, verbose_name='Year')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='h5pp.h5p_contents')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLearnerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('passed', 'Passed'), ('failed', 'Failed'), ('completed', 'Completed')], default='started', max_length=100, verbose_name='Status')),
                ('status_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_status', to='courses.CourseVersion')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_status', to='courses.Learner', verbose_name='Learner')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCourseLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('course_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_library', to='courses.CourseLibrary')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_libraries', to='courses.Organization')),
            ],
            options={
                'unique_together': {('organization', 'course_library')},
            },
        ),
        migrations.CreateModel(
            name='CourseLibraryCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('course_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.CourseLibrary')),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='courses.CourseVersion')),
            ],
            options={
                'unique_together': {('course_version', 'course_library')},
            },
        ),
    ]
