# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselearnerstatus',
            name='course',
        ),
        migrations.AddField(
            model_name='courselearnerstatus',
            name='course_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseVersion'),
            preserve_default=False,
        ),
    ]
