# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170825_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationcourselibrary',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
